project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: overview.html
        text: Overview
      - href: methodology.qmd
        text: Methotology
      - href: analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Results & Discussion
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

